/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MasterService_constants.h"

namespace MasterService {

const MasterServiceConstants g_MasterService_constants;

MasterServiceConstants::MasterServiceConstants() {
}

} // namespace

