/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MasterService_CONSTANTS_H
#define MasterService_CONSTANTS_H

#include "MasterService_types.h"

namespace MasterService {

class MasterServiceConstants {
 public:
  MasterServiceConstants();

};

extern const MasterServiceConstants g_MasterService_constants;

} // namespace

#endif
