/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SharedService_constants.h"

namespace SharedService {

const SharedServiceConstants g_SharedService_constants;

SharedServiceConstants::SharedServiceConstants() {
}

} // namespace

