/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SharedService_CONSTANTS_H
#define SharedService_CONSTANTS_H

#include "SharedService_types.h"

namespace SharedService {

class SharedServiceConstants {
 public:
  SharedServiceConstants();

};

extern const SharedServiceConstants g_SharedService_constants;

} // namespace

#endif
