/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WorkerService_CONSTANTS_H
#define WorkerService_CONSTANTS_H

#include "WorkerService_types.h"

namespace WorkerService {

class WorkerServiceConstants {
 public:
  WorkerServiceConstants();

};

extern const WorkerServiceConstants g_WorkerService_constants;

} // namespace

#endif
