/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "WorkerService_constants.h"

namespace WorkerService {

const WorkerServiceConstants g_WorkerService_constants;

WorkerServiceConstants::WorkerServiceConstants() {
}

} // namespace

